# Generated by Django 5.2.7 on 2025-11-05 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(db_column='subject_code', max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_column='subject_name', max_length=100)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('parent_task', models.ForeignKey(blank=True, db_column='parent_task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tasks', to='db_model.task')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(db_column='comment_id', primary_key=True, serialize=False)),
                ('content', models.CharField(db_column='content', max_length=200)),
                ('created_date', models.DateTimeField(db_column='created_date')),
                ('task', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='db_model.task')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('subject1', models.ForeignKey(blank=True, db_column='subject1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subject1', to='db_model.subject')),
                ('subject2', models.ForeignKey(blank=True, db_column='subject2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subject2', to='db_model.subject')),
                ('subject3', models.ForeignKey(blank=True, db_column='subject3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subject3', to='db_model.subject')),
                ('subject4', models.ForeignKey(blank=True, db_column='subject4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subject4', to='db_model.subject')),
                ('subject5', models.ForeignKey(blank=True, db_column='subject5', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subject5', to='db_model.subject')),
                ('subject6', models.ForeignKey(blank=True, db_column='subject6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subject6', to='db_model.subject')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('role', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
            options={
                'db_table': 'ProjectMember',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('comment', models.ForeignKey(db_column='comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_model.comment')),
                ('task', models.ForeignKey(db_column='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_model.task')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_model.user')),
            ],
            options={
                'db_table': 'Log',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(db_column='file_id', primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, db_column='file_name', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.task')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
            options={
                'db_table': 'File',
            },
        ),
        migrations.CreateModel(
            name='DirectMessageRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user1', to='db_model.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user2', to='db_model.user')),
            ],
            options={
                'db_table': 'DirectMessageRoom',
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.directmessageroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
            options={
                'db_table': 'DirectMessage',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.user'),
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.RESTRICT, related_name='user_subject_links', to='db_model.subject')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_subject_links', to='db_model.user')),
            ],
            options={
                'db_table': 'UserSubject',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='users', through='db_model.UserSubject', to='db_model.subject', verbose_name='수강 과목들'),
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('tm_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.project')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.task')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='db_model.user')),
            ],
            options={
                'db_table': 'TaskManager',
                'unique_together': {('user', 'project', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(db_column='post_id', help_text='게시글ID (PK)', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', help_text='제목', max_length=255)),
                ('content', models.TextField(db_column='content', help_text='내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', help_text='작성일시')),
                ('subject', models.ForeignKey(db_column='subject_code', help_text='과목코드 (FK → Subject)', on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='db_model.subject')),
                ('author', models.ForeignKey(db_column='author_id', help_text='작성자 (FK → User)', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='db_model.user')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
                'db_table': 'Post',
                'indexes': [models.Index(fields=['subject'], name='idx_post_subject'), models.Index(fields=['author'], name='idx_post_author')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='db_model.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to='db_model.user')),
            ],
            options={
                'db_table': 'FavoriteProject',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
