# Generated by Django 5.2.7 on 2025-11-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='directmessage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='directmessageroom',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False, 'verbose_name': '게시글', 'verbose_name_plural': '게시글 목록'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taskmanager',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersubject',
            options={'managed': False},
        ),
    ]
